# ==========================================
# Application & Server Configuration
# ==========================================
quarkus.application.name=order-service
quarkus.http.port=8080

# Disable DevServices
quarkus.devservices.enabled=false
quarkus.kogito.dev-services.enabled=false

# Enable Swagger UI across all environments
quarkus.swagger-ui.always-include=true

# ==========================================
# Database Configuration (PostgreSQL)
# ==========================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:postgres}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:12345678}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/order_db}

# Hibernate ORM & Panache Configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format_sql=true

# Kogito Process Persistence (Stores BPMN states in Postgres)
quarkus.kogito.persistence.type=postgresql

# ==========================================
# Kafka Messaging Configuration
# ==========================================
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Incoming Channel: orders-in
mp.messaging.incoming.orders-in.connector=smallrye-kafka
mp.messaging.incoming.orders-in.topic=orders-in
mp.messaging.incoming.orders-in.auto.offset.reset=earliest
mp.messaging.incoming.orders-in.value.deserializer=org.apekking.dto.OrderEventDeserializer

# Outgoing Channel: orders-out
mp.messaging.outgoing.orders-out.connector=smallrye-kafka
mp.messaging.outgoing.orders-out.topic=orders-out
mp.messaging.outgoing.orders-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer